version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '08:00'
      timezone: Europe/London
    groups:
      compatible-updates:
        patterns:
          - '*'
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /cli
    schedule:
      interval: weekly
      day: monday
      time: '08:15'
      timezone: Europe/London
    groups:
      compatible-updates:
        patterns:
          - '*'
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
