import type { CuratedProfile } from './types';

export const ELECTRONICS_TERMS = [
  'arduino',
  'raspberry',
  'esp32',
  'esp8266',
  'microcontroller',
  'development',
  'board',
  'breadboard',
  'resistor',
  'capacitor',
  'transistor',
  'diode',
  'sensor',
  'module',
  'pcb',
  'solder',
  'multimeter',
  'oscilloscope',
  'connector',
  'voltage',
  'current',
  'gpio',
  'electronic',
  'electronics',
];

export const LOW_SIGNAL_TERMS = [
  'logo',
  'icon',
  'clipart',
  'vector',
  'emoji',
  'symbol',
  'wallpaper',
  'poster',
  'sticker',
  'meme',
  'cartoon',
  'drawing',
  '3d render',
  'mockup',
  'toy',
];

export const CURATED_PROFILES: CuratedProfile[] = [
  {
    id: 'arduino-uno',
    intent: 'board',
    aliases: ['arduino uno', 'uno r3', 'arduino r3', 'arduino'],
    preferredQuery: 'arduino uno r3 development board closeup photo',
    fallbackQuery: 'arduino uno board',
    relevanceTokens: ['arduino', 'uno', 'r3', 'board', 'microcontroller'],
  },
  {
    id: 'esp32-devkit',
    intent: 'board',
    aliases: ['esp32', 'esp32 devkit', 'esp32 wroom', 'esp32 board'],
    preferredQuery: 'esp32 devkit v1 development board closeup',
    fallbackQuery: 'esp32 development board',
    relevanceTokens: ['esp32', 'devkit', 'board', 'wroom', 'module'],
  },
  {
    id: 'raspberry-pi-4',
    intent: 'board',
    aliases: ['raspberry pi 4', 'rpi 4', 'pi 4', 'raspberry pi'],
    preferredQuery: 'raspberry pi 4 model b board closeup',
    fallbackQuery: 'raspberry pi board',
    relevanceTokens: ['raspberry', 'pi', 'model', 'board', 'ports'],
  },
  {
    id: 'breadboard',
    intent: 'connector',
    aliases: ['breadboard', 'solderless breadboard'],
    preferredQuery: 'solderless breadboard closeup electronics',
    fallbackQuery: 'breadboard prototyping board',
    relevanceTokens: ['breadboard', 'solderless', 'prototyping'],
  },
  {
    id: 'multimeter',
    intent: 'tool',
    aliases: ['multimeter', 'digital multimeter', 'dmm'],
    preferredQuery: 'digital multimeter electronics bench tool',
    fallbackQuery: 'multimeter closeup',
    relevanceTokens: ['multimeter', 'digital', 'meter', 'bench'],
  },
  {
    id: 'servo-motor-sg90',
    intent: 'actuator',
    aliases: ['servo motor', 'sg90 servo', 'micro servo', 'servo'],
    preferredQuery: 'sg90 micro servo motor electronics closeup',
    fallbackQuery: 'servo motor module',
    relevanceTokens: ['servo', 'motor', 'sg90', 'actuator', 'horn'],
  },
  {
    id: 'stepper-28byj48',
    intent: 'actuator',
    aliases: ['stepper motor', '28byj-48', '28byj48'],
    preferredQuery: '28byj-48 stepper motor module electronics closeup',
    fallbackQuery: 'stepper motor electronics',
    relevanceTokens: ['stepper', 'motor', '28byj', 'driver'],
  },
  {
    id: 'dc-motor',
    intent: 'actuator',
    aliases: ['dc motor', 'brushed dc motor', 'mini dc motor'],
    preferredQuery: 'mini dc motor electronics project closeup',
    fallbackQuery: 'dc motor closeup',
    relevanceTokens: ['dc', 'motor', 'shaft', 'actuator'],
  },
  {
    id: 'relay-module',
    intent: 'actuator',
    aliases: ['relay module', '5v relay', 'relay board', 'relay'],
    preferredQuery: '5v relay module electronics board closeup',
    fallbackQuery: 'relay module board',
    relevanceTokens: ['relay', 'module', 'board', 'coil', 'contacts'],
  },
  {
    id: 'ultrasonic-hcsr04',
    intent: 'sensor',
    aliases: ['hc-sr04', 'hcsr04', 'ultrasonic sensor', 'distance sensor'],
    preferredQuery: 'hc-sr04 ultrasonic distance sensor module closeup',
    fallbackQuery: 'ultrasonic sensor module',
    relevanceTokens: ['ultrasonic', 'sensor', 'hc-sr04', 'distance'],
  },
  {
    id: 'dht11-sensor',
    intent: 'sensor',
    aliases: ['dht11', 'temperature humidity sensor', 'dht sensor'],
    preferredQuery: 'dht11 temperature humidity sensor module closeup',
    fallbackQuery: 'dht11 sensor module',
    relevanceTokens: ['dht11', 'temperature', 'humidity', 'sensor'],
  },
  {
    id: 'pir-hc-sr501',
    intent: 'sensor',
    aliases: ['pir sensor', 'motion sensor', 'hc-sr501'],
    preferredQuery: 'hc-sr501 pir motion sensor module closeup',
    fallbackQuery: 'pir motion sensor module',
    relevanceTokens: ['pir', 'motion', 'sensor', 'module'],
  },
  {
    id: 'oled-ssd1306',
    intent: 'display',
    aliases: ['oled display', 'ssd1306', '0.96 oled'],
    preferredQuery: 'ssd1306 oled display module electronics closeup',
    fallbackQuery: 'oled display module',
    relevanceTokens: ['oled', 'ssd1306', 'display', 'module'],
  },
  {
    id: 'lcd-1602',
    intent: 'display',
    aliases: ['lcd 1602', '1602 lcd', 'character lcd', 'lcd module'],
    preferredQuery: '1602 lcd character display module closeup',
    fallbackQuery: 'lcd 1602 module',
    relevanceTokens: ['lcd', '1602', 'display', 'character'],
  },
  {
    id: 'potentiometer',
    intent: 'passive',
    aliases: ['potentiometer', 'pot', 'variable resistor'],
    preferredQuery: 'rotary potentiometer electronics component closeup',
    fallbackQuery: 'potentiometer component',
    relevanceTokens: ['potentiometer', 'variable', 'resistor', 'rotary'],
  },
  {
    id: 'resistor',
    intent: 'passive',
    aliases: ['resistor', 'resistors', 'through-hole resistor'],
    preferredQuery: 'through-hole resistor electronics component closeup',
    fallbackQuery: 'resistor component',
    relevanceTokens: ['resistor', 'ohm', 'component', 'color bands'],
  },
  {
    id: 'electrolytic-capacitor',
    intent: 'passive',
    aliases: ['capacitor', 'electrolytic capacitor', 'capacitors'],
    preferredQuery: 'electrolytic capacitor electronics component closeup',
    fallbackQuery: 'capacitor component',
    relevanceTokens: ['capacitor', 'electrolytic', 'uf', 'component'],
  },
  {
    id: 'led-component',
    intent: 'passive',
    aliases: ['led', 'led diode', 'light emitting diode'],
    preferredQuery: '5mm led diode electronics component closeup',
    fallbackQuery: 'led component',
    relevanceTokens: ['led', 'diode', 'component', 'anode', 'cathode'],
  },
  {
    id: 'buzzer-module',
    intent: 'actuator',
    aliases: ['buzzer', 'active buzzer', 'passive buzzer', 'buzzer module'],
    preferredQuery: 'buzzer module electronics closeup',
    fallbackQuery: 'piezo buzzer module',
    relevanceTokens: ['buzzer', 'piezo', 'module', 'sound'],
  },
  {
    id: '2n2222-transistor',
    intent: 'chip',
    aliases: ['2n2222', 'transistor', 'npn transistor', 'to-92 transistor'],
    preferredQuery: '2n2222 npn transistor to-92 package closeup',
    fallbackQuery: 'npn transistor component',
    relevanceTokens: ['2n2222', 'npn', 'transistor', 'to-92'],
  },
  {
    id: 'l298n-driver',
    intent: 'power',
    aliases: ['l298n', 'motor driver', 'l298n module', 'h-bridge module'],
    preferredQuery: 'l298n motor driver module board closeup',
    fallbackQuery: 'motor driver module electronics',
    relevanceTokens: ['l298n', 'driver', 'module', 'h-bridge', 'motor'],
  },
  {
    id: 'lm2596-buck',
    intent: 'power',
    aliases: ['lm2596', 'buck converter', 'dc-dc converter', 'step down module'],
    preferredQuery: 'lm2596 buck converter module electronics closeup',
    fallbackQuery: 'buck converter module',
    relevanceTokens: ['lm2596', 'buck', 'converter', 'module', 'dc-dc'],
  },
  {
    id: 'jumper-wires',
    intent: 'connector',
    aliases: ['jumper wires', 'dupont wires', 'dupont cable', 'jumper cable'],
    preferredQuery: 'dupont jumper wires electronics breadboard closeup',
    fallbackQuery: 'jumper wires electronics',
    relevanceTokens: ['jumper', 'dupont', 'wires', 'breadboard'],
  },
  {
    id: 'usb-c-cable',
    intent: 'connector',
    aliases: ['usb c cable', 'usb-c cable', 'usb cable', 'type c cable'],
    preferredQuery: 'usb-c cable data power electronics closeup',
    fallbackQuery: 'usb c cable connector',
    relevanceTokens: ['usb-c', 'cable', 'connector', 'type-c'],
  },
  {
    id: 'stm32-blue-pill',
    intent: 'board',
    aliases: ['stm32', 'blue pill', 'stm32 blue pill', 'stm32f103'],
    preferredQuery: 'stm32f103 blue pill development board closeup',
    fallbackQuery: 'stm32 development board',
    relevanceTokens: ['stm32', 'f103', 'blue', 'pill', 'board'],
  },
  {
    id: 'nodemcu-esp8266',
    intent: 'board',
    aliases: ['nodemcu', 'esp8266 nodemcu', 'esp8266 board', 'esp-12e'],
    preferredQuery: 'nodemcu esp8266 development board closeup',
    fallbackQuery: 'esp8266 nodemcu board',
    relevanceTokens: ['nodemcu', 'esp8266', 'board', 'wifi'],
  },
  {
    id: 'ws2812b-neopixel',
    intent: 'actuator',
    aliases: ['ws2812b', 'neopixel', 'addressable led', 'rgb led strip'],
    preferredQuery: 'ws2812b neopixel addressable led strip closeup',
    fallbackQuery: 'neopixel led module',
    relevanceTokens: ['ws2812b', 'neopixel', 'addressable', 'led', 'rgb'],
  },
  {
    id: 'rotary-encoder-ky040',
    intent: 'sensor',
    aliases: ['rotary encoder', 'ky-040', 'ky040 encoder', 'encoder module'],
    preferredQuery: 'ky-040 rotary encoder module closeup',
    fallbackQuery: 'rotary encoder module electronics',
    relevanceTokens: ['encoder', 'rotary', 'ky-040', 'module'],
  },
  {
    id: 'joystick-module',
    intent: 'sensor',
    aliases: ['joystick module', 'ps2 joystick', 'analog joystick'],
    preferredQuery: 'ps2 analog joystick module electronics closeup',
    fallbackQuery: 'joystick module board',
    relevanceTokens: ['joystick', 'analog', 'module', 'x y'],
  },
  {
    id: 'ldr-photoresistor',
    intent: 'sensor',
    aliases: ['ldr', 'photoresistor', 'light sensor resistor'],
    preferredQuery: 'ldr photoresistor light sensor component closeup',
    fallbackQuery: 'photoresistor sensor module',
    relevanceTokens: ['ldr', 'photoresistor', 'light', 'sensor'],
  },
  {
    id: 'soil-moisture-sensor',
    intent: 'sensor',
    aliases: ['soil moisture sensor', 'hygrometer sensor', 'soil sensor module'],
    preferredQuery: 'soil moisture sensor module electronics closeup',
    fallbackQuery: 'soil moisture sensor board',
    relevanceTokens: ['soil', 'moisture', 'sensor', 'module'],
  },
  {
    id: 'ina219-current-sensor',
    intent: 'sensor',
    aliases: ['ina219', 'current sensor module', 'voltage current sensor'],
    preferredQuery: 'ina219 current sensor module closeup',
    fallbackQuery: 'ina219 module board',
    relevanceTokens: ['ina219', 'current', 'sensor', 'module', 'i2c'],
  },
  {
    id: 'ds3231-rtc',
    intent: 'sensor',
    aliases: ['ds3231', 'rtc module', 'real time clock module'],
    preferredQuery: 'ds3231 rtc module electronics closeup',
    fallbackQuery: 'rtc module board',
    relevanceTokens: ['ds3231', 'rtc', 'clock', 'module'],
  },
  {
    id: 'hx711-load-cell',
    intent: 'sensor',
    aliases: ['hx711', 'load cell amplifier', 'load cell module'],
    preferredQuery: 'hx711 load cell amplifier module closeup',
    fallbackQuery: 'hx711 module',
    relevanceTokens: ['hx711', 'load', 'cell', 'amplifier', 'module'],
  },
  {
    id: 'micro-sd-module',
    intent: 'connector',
    aliases: ['micro sd module', 'sd card module', 'microsd breakout'],
    preferredQuery: 'micro sd card module spi breakout closeup',
    fallbackQuery: 'sd card module electronics',
    relevanceTokens: ['micro', 'sd', 'card', 'module', 'spi'],
  },
  {
    id: 'mosfet-irfz44n',
    intent: 'chip',
    aliases: ['mosfet', 'irfz44n', 'n channel mosfet', 'power mosfet'],
    preferredQuery: 'irfz44n n-channel mosfet transistor closeup',
    fallbackQuery: 'power mosfet transistor component',
    relevanceTokens: ['mosfet', 'irfz44n', 'transistor', 'power'],
  },
  {
    id: 'lm358-opamp',
    intent: 'chip',
    aliases: ['lm358', 'op amp', 'operational amplifier ic', 'opamp ic'],
    preferredQuery: 'lm358 operational amplifier ic dip package closeup',
    fallbackQuery: 'op amp ic component',
    relevanceTokens: ['lm358', 'opamp', 'operational', 'amplifier', 'ic'],
  },
];
